### ISSUE TITLE
Support other dialects

### ISSUE THREAD

**Issue by jbrumwell** [bjyoungblood/mariner#8]
What are your thoughts on supporting dialects? I have a direct need to manage both sql and cypher migrations and would be awesome if Mariner could handle both? Are you for this if I create a PR for it?

**Comment by bjyoungblood** [comment]
That seems like a reasonable goal to me. It would be nice to be able to support non-sql databases or even have the migration state storage backend be pluggable.

**Comment by jbrumwell** [comment]
With it being a cli, hard to make it configurable considering these plugins will require some configuration ie: connection strings.  What are your thoughts on a `.mariner` type file that allows for plugins.  

```
{
  plugins: [
    'sql',  // translates to mariner-sql
    'cypher',
    'mariner-js',
  ],

  backend : 'sql',

  sql: {
    connection : '',
  }

  cypher : {
    connection : '',
  }
}
```

Or do you see a better approach?

**Comment by bjyoungblood** [comment]
That makes sense to me, but I think it should be evaluated as a javascript file and not just flat json. That way it's possible to access environment variables (or some other source).

**Comment by bjyoungblood** [comment]
It would also be nice to have a command to generate an empty config (or maybe just have a yeoman generator).
